<template>
    <div style="overflow-x: hidden !important;" data-proslinks-homepage>
        <!--Header-->
        <header-nav-bar></header-nav-bar>
        <header id="header" class="header">
            <div class="header-content"></div>
        </header>
        <!--Header-->


        <!--Body-->
        <div class="container mt-5 mb-5 pt-4 pb-4">
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style='font-family:"Lato",sans-serif;color:red;'>PROFESSIONAL LINKS, LLC</span></strong></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style='font-family:"Lato",sans-serif;color:red;'>Website Terms and Conditions of Use</span></strong></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style='font-family:"Lato",sans-serif;color:red;'>Revised as of January 15, 2021</span></strong></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Lato",sans-serif;color:black;'>Welcome to www.skillpeers.com (the &ldquo;Website&rdquo;). &nbsp;PROFESSIONAL LINKS, LLC provides access to the Website to you subject to the following terms and conditions. In return for accessing the Website, you agree to be bound by these terms and conditions of use without limitation or qualification. This is a legally binding agreement between you as the user(s) of the Website (hereinafter may be referred to as &ldquo;you&rdquo;, &ldquo;your&rdquo;, &ldquo;User&rdquo;, or &ldquo;Visitor&rdquo;) and PROFESSIONAL LINKS, LLC (hereinafter may be referred to as &ldquo;we,&apos;&apos; &ldquo;our,&rdquo; or &ldquo;www.skillpeers.com&rdquo;). If you do not intend to be legally bound by these terms and conditions of use, do not access or use the Website. Essentially, if you visit the Website, you accept these terms and conditions of use. Please read them carefully.</span></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style='font-family:"Lato",sans-serif;color:black;'>Geographic Scope</span></strong></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Lato",sans-serif;color:black;'>The Website may be viewed throughout the United States as well as internationally, and may contain references to services not available in all States of the United States or in all countries. References to a particular service does not imply that we intend to make such &nbsp;services available in such states or countries. No warranty or representation is given that a particular product or service will be available for all website visitors.&nbsp;</span></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style='font-family:"Lato",sans-serif;color:black;'>Service Descriptions</span></strong></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Lato",sans-serif;color:black;'>We attempt to be as accurate as possible in describing our company and the services we offer; however, we do not warrant that the service descriptions or other content of this Website is accurate, complete, reliable, current, or error-free.</span></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style='font-family:"Lato",sans-serif;color:black;'>Electronic Communications</span></strong></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Lato",sans-serif;color:black;'>When you contact us through the Website, or send an email to an address located on the Website, you are communicating with us electronically. You consent to receive a response from us electronically. We may communicate with you by email or by posting notices on the Website. For example, you acknowledge and agree that we may amend these terms and conditions at any time by posting the amended and restated terms on the Website. By continuing to use the Website, you agree that the amended Terms will apply to you.&nbsp;</span></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style='font-family:"Lato",sans-serif;color:black;'>General Use</span></strong></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Lato",sans-serif;color:black;'>If you use the Website, you are responsible for maintaining the confidentiality of your personal information, for restricting access to your computer, and you agree to accept responsibility for all activities that occur when accessing our Website via your computer. As a condition of your access to and use of the Website, you agree that you will comply with all applicable laws and regulations. You agree to use the Website solely for your own private and internal purposes. You agree that (a) you will not copy, reproduce, download, re-publish, sell, distribute or resell any information, text, images, graphics, or other information available on or through the Website (the &ldquo;Website Content&rdquo;), and (b) you will not copy, reproduce, download, compile or otherwise use any Website Content for the purposes of operating a business that competes with PROFESSIONAL LINKS, LLC, or otherwise commercially exploiting the Website Content. You agree further not to undertake any action to undermine the integrity of our computer systems or networks and/or attempt to gain unauthorized access to such computer systems or networks. &nbsp;The use of this website is at the discretion of PROFESSIONAL LINKS, LLC; and PROFESSIONAL LINKS, LLC may terminate your use of this website at any time.</span></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style='font-family:"Lato",sans-serif;color:black;'>Visitor Responsibilities</span></strong></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Lato",sans-serif;color:black;'>You represent, warrant and agree that (a) you have full power and authority to accept these terms and conditions; (b) you use the Website for your own personal or business purposes only; (c) you are over the age of eighteen (18), and (d) all information that you provide through our contact forms is accurate.&nbsp;</span></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Lato",sans-serif;color:black;'>You further warrant and agree that (a) you shall be solely responsible for obtaining all necessary third party licenses and permissions regarding any information you submit; (b) any information that you provide us does not infringe or violate any of the copyright, patent, trademark, trade name, trade secrets or any other personal or proprietary rights of any third party (&ldquo;Third Party Rights&rdquo;); (c) you have the right and authority to secure any services requested through our contact forms, messages, emails, telephone numbers and the like; and (d) &nbsp;you will indemnify PROFESSIONAL LINKS, LLC against any claim(s) resulting from content you supply.&nbsp;</span></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Lato",sans-serif;color:black;'>You further represent, warrant and agree that any information that you submit shall: (a) be true, accurate, complete and lawful; (b) not be false, misleading or deceptive; (c) not contain information that is defamatory, libelous, threatening or harassing, obscene, objectionable, offensive, sexually explicit or harmful; (d) not contain information that is discriminatory or promotes discrimination based on race, sex, religion, nationality, disability, sexual orientation or age; (e) not violate these terms and conditions; (f) not violate any applicable laws and regulations or promote any activities which may violate any applicable laws and regulations; and/or (g) not contain any link directly or indirectly to any other websites which includes any content that may violate these terms.</span></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Lato",sans-serif;color:black;'>By transmitting or posting any non-confidential information to skillpeers.com/#/home or PROFESSIONAL LINKS, LLC, you grant PROFESSIONAL LINKS, LLC a non-exclusive, royalty-free, perpetual, irrevocable, and fully sub-licensable right to use such information for any purpose, including, but not limited to, its reproduction, modification, adaptation, publication, translation, use in derivative works, distribution, and display throughout the world in any media. You also grant PROFESSIONAL LINKS, LLC and sublicensees the right, at their sole discretion but without any obligation to do so, to use the name you submit in connection with such content. You further agree that the license granted herein includes the right to use or authorize use of any ideas, concepts, know-how or techniques contained in such information for any purpose whatsoever, including, but not limited to, developing, manufacturing and marketing products or services incorporating such information.&nbsp;</span></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Lato",sans-serif;color:black;'>You agree that neither PROFESSIONAL LINKS, LLC nor its licensees will be liable to you for any use of any information you submit. PROFESSIONAL LINKS, LLC has the right, but not the obligation, to monitor and edit or remove any content.</span></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Lato",sans-serif;color:black;'>You acknowledge and agree that you, the user, are solely responsible for any information you submit to PROFESSIONAL LINKS, LLC or this website and further agree, that PROFESSIONAL LINKS, LLC has no responsibility for the content of any such submissions, including their legality, reliability and appropriateness.</span></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style='font-family:"Lato",sans-serif;color:black;'>Cooperation with Law Enforcement or Legal Proceeding</span></strong></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Lato",sans-serif;color:black;'>We reserve the right to cooperate fully with governmental authorities, private investigators and/or injured third parties in the investigation of any suspected criminal or civil wrongdoing. Further, PROFESSIONAL LINKS, LLC may disclose any communications or contact information provided to us, if requested by a government or law enforcement body, an injured third party, or as a result of a subpoena or other legal action. We shall not be liable for damage that results arising from such disclosure, and you agree not to bring any action or claim against us for such disclosure. You agree to indemnify PROFESSIONAL LINKS, LLC, our affiliates, directors, employees, agents and representatives and to hold them harmless from any and all damages, losses, claims and liabilities (including legal costs on a full indemnity basis) which may arise from your use of the Website or from your breach of these terms.</span></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style='font-family:"Lato",sans-serif;color:black;'>License and Website Access</span></strong></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Lato",sans-serif;color:black;'>We grant you a nonexclusive, non transferable, revocable limited right and license to access the Website and the material provided hereon. This license does not include any rights of resale or commercial use of the Website or its contents; any collection and use of any descriptions of services; any derivative use of the Website or its contents; any downloading or copying of information for the benefit of another company; or any use of data mining, robots, or similar data gathering and extraction tools. The Website may not be reproduced, duplicated, copied, sold, resold, visited, or otherwise exploited for any commercial purpose. Any unauthorized use terminates the permission or license granted by PROFESSIONAL LINKS, LLC</span></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Lato",sans-serif;color:black;'>You are granted a limited, revocable, and nonexclusive right to create a hyperlink to the homepage of PROFESSIONAL LINKS, LLC so long as the link does not portray PROFESSIONAL LINKS, LLC or its services, in a false, misleading, derogatory, or otherwise offensive matter. You may not use any proprietary graphic, trade name, trademark, or service mark of PROFESSIONAL LINKS, LLC or any of its affiliates as part of the link without the express, written consent of PROFESSIONAL LINKS, LLC</span></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style='font-family:"Lato",sans-serif;color:black;'>Links</span></strong></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Lato",sans-serif;color:black;'>These terms and conditions of use apply only to this Website, and not to the websites of any other person or entity. We may provide links to other websites or resources (such as, but not limited to, Facebook, Twitter, Instagram, Pinterest, and LinkedIn). You acknowledge and agree that we are not responsible for the availability of such external websites or resources, and do not endorse (and are not responsible or liable for) any content, advertising, products, services, or other materials on or available from such other websites or resources. You further acknowledge and agree that, under no circumstances, will we be held responsible or liable, directly or indirectly, for any loss or damage that is caused or alleged to have been caused to you in connection with your use of, or reliance on, any content, advertisements, or other resources available from any other website (regardless of whether we directly or indirectly link to such content, advertisements, products, services, or other resources). You should direct any concerns with respect to any other websites to that website&rsquo;s administrator.</span></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style='font-family:"Lato",sans-serif;color:black;'>Copyright</span></strong></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Lato",sans-serif;color:black;'>All content included on the Website, including, but not limited to, text, design, graphics, logos, button icons, images, and code, is the property of PROFESSIONAL LINKS, LLC, and is protected by United States and international copyright laws. Nothing contained on the Website should be construed as granting, by implication, estoppel, or otherwise, any license or right to use any of the copyrighted works displayed or contained in the Website without our express, written consent.</span></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style='font-family:"Lato",sans-serif;color:black;'>Trademarks</span></strong></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Lato",sans-serif;color:black;'>PROFESSIONAL LINKS, LLC may own certain registered and unregistered trademarks in the United States or other countries, including but not limited to PROFESSIONAL LINKS, LLC and various stylized versions thereof.</span></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Lato",sans-serif;color:black;'>The registered and unregistered trademarks, service marks, trade names, graphics, logos, page headers, button icons, scripts, trade dress, or other indicia of trade origin of PROFESSIONAL LINKS, LLC or its affiliates may not be used in connection with any business, product, or service in any manner that is likely to cause confusion among customers, the trade, or the public, or in any manner that disparages or discredits PROFESSIONAL LINKS, LLC or any of its affiliates. All other trademarks, service marks, trade names, and logos not owned by PROFESSIONAL LINKS, LLC that appear on the Website are the property of their respective owners, who may or may not be affiliated with, connected to, or sponsored by PROFESSIONAL LINKS, LLC Nothing contained on the Website should be construed as granting, by implication, estoppel or otherwise, any license or right to use any of the trademarks, service marks, trade names, graphics, logos, page headers, button icons, scripts, trade dress, or other indicia of trade origin of PROFESSIONAL LINKS, LLC displayed or contained in the Website without our express, written consent.</span></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:.0001pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style='font-family:"Lato",sans-serif;color:black;'>Patents</span></strong></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Lato",sans-serif;color:black;'>One or more patents may apply to the Website and the services accessible via the Website. Nothing contained on the Website should be construed as granting, by implication, estoppel or otherwise, any license or right to use any of the foregoing patents, licensed patents, or patentable inventions contained therein without our expressed written consent.&nbsp;</span></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style='font-family:"Lato",sans-serif;color:black;'>Copyright Complaints</span></strong></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Lato",sans-serif;color:black;'>We respect the intellectual property rights of others, and we ask our users to do the same. If you believe that your work has been copied in a way that constitutes copyright infringement, please provide the following information to PROFESSIONAL LINKS, LLC as specified below:</span></p>
          <ul style="margin-bottom:0in;margin-top:0in;" type="disc">
            <li style='margin-top:0in;margin-right:0in;margin-bottom:.0001pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;color:black;vertical-align:     baseline;'><span style='font-family:"Lato",sans-serif;'>An electronic or physical signature of the person authorized to act on behalf of the owner of the copyright interest;</span></li>
            <li style='margin-top:0in;margin-right:0in;margin-bottom:.0001pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;color:black;vertical-align:     baseline;'><span style='font-family:"Lato",sans-serif;'>A description of the copyrighted work that you claim has been infringed upon;</span></li>
            <li style='margin-top:0in;margin-right:0in;margin-bottom:.0001pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;color:black;vertical-align:     baseline;'><span style='font-family:"Lato",sans-serif;'>A description of where the material that you claim is infringing is located on the Website;</span></li>
            <li style='margin-top:0in;margin-right:0in;margin-bottom:.0001pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;color:black;vertical-align:     baseline;'><span style='font-family:"Lato",sans-serif;'>Your address, telephone number, and e-mail address;</span></li>
            <li style='margin-top:0in;margin-right:0in;margin-bottom:.0001pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;color:black;vertical-align:     baseline;'><span style='font-family:"Lato",sans-serif;'>A statement that you have a good faith belief that the disputed use is not authorized by the copyright owner, its agent, and or the law; and</span></li>
            <li style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;color:black;vertical-align:baseline;'><span style='font-family:"Lato",sans-serif;'>A statement by you, made under penalty of perjury, that the above information in your notice is accurate, and that you are the copyright owner or authorized to act on the copyright owner&rsquo;s behalf.</span></li>
          </ul>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Lato",sans-serif;color:black;'>You may send any notices, including notices of copyright infringement under the Digital Millennium Copyright Act, to us at PROFESSIONAL LINKS, LLC, 11 Windrose, Aliso Viejo, CA 92656.</span></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Lato",sans-serif;color:black;'>Please note that this procedure is exclusively for notifying us that your copyrighted material may have been infringed. All intellectual property infringement claims shall be made under penalty of perjury.</span></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Lato",sans-serif;color:black;'>THIS POLICY IS INTENDED TO COMPLY FULLY WITH THE REQUIREMENTS OF THE ONLINE COPYRIGHT INFRINGEMENT LIABILITY LIMITATION ACT.</span></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style='font-family:"Lato",sans-serif;color:black;'>Disclaimer</span></strong></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Lato",sans-serif;color:black;'>THE INFORMATION ON THIS SITE IS PROVIDED ON AN &quot;AS IS,&quot; &quot;AS AVAILABLE&quot; BASIS. YOU AGREE THAT USE OF THIS SITE IS AT YOUR SOLE RISK. PROFESSIONAL LINKS, LLC DISCLAIMS ALL WARRANTIES OF ANY KIND, INCLUDING BUT NOT LIMITED TO ANY EXPRESS WARRANTIES, STATUTORY WARRANTIES, AND ANY IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. TO THE EXTENT YOUR JURISDICTION DOES NOT ALLOW LIMITATIONS ON WARRANTIES, THIS LIMITATION MAY NOT APPLY TO YOU. YOUR SOLE AND EXCLUSIVE REMEDY RELATING TO YOUR USE OF THE SITE SHALL BE TO DISCONTINUE USING THE SITE.</span></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style='font-family:"Lato",sans-serif;color:black;'>Limitation of Liability</span></strong></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Lato",sans-serif;color:black;'>UNDER NO CIRCUMSTANCES WILL PROFESSIONAL LINKS, LLC BE LIABLE OR RESPONSIBLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, CONSEQUENTIAL (INCLUDING DAMAGES FROM LOSS OF BUSINESS, LOST PROFITS, LITIGATION, OR THE LIKE), SPECIAL, EXEMPLARY, PUNITIVE, OR OTHER DAMAGES, UNDER ANY LEGAL THEORY, ARISING OUT OF OR IN ANY WAY RELATING TO THE SITE, YOUR SITE USE, OR THE CONTENT, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. YOUR SOLE REMEDY FOR DISSATISFACTION WITH THE SITE AND/OR CONTENT IS TO CEASE ALL OF YOUR SITE USE.</span></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Lato",sans-serif;color:black;'>You may have additional rights under certain laws (including consumer laws) which do not allow the exclusion of implied warranties, or the exclusion or limitation of certain damages. If these laws apply to you, the exclusions or limitations in this Agreement that directly conflict with such laws may not apply to you.</span></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style='font-family:"Lato",sans-serif;color:black;'>Disclaimers and Warranties</span></strong></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Lato",sans-serif;color:black;'>The testimonials, reviews, comments, &nbsp;and client satisfaction stories herein provided on the Website reflect the real life experiences of individuals and businesses who used our services. However, individual results may vary. &nbsp;</span></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Lato",sans-serif;color:black;'>Please keep in mind that we cannot guarantee particular results for future clients based on successes and satisfaction of &nbsp;past clients.</span></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Lato",sans-serif;color:black;'>We do not claim, nor should the reader assume, that any individual experience recounted is typical or representative of what any other consumer might experience. Testimonials and client success stories are not necessarily representative of what anyone else using our services may experience.&nbsp;</span></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Lato",sans-serif;color:black;'>SOME JURISDICTIONS PROVIDE FOR CERTAIN WARRANTIES, LIKE THE IMPLIED WARRANTY OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. TO THE EXTENT PERMITTED BY LAW, WE EXCLUDE ALL WARRANTIES.</span></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style='font-family:"Lato",sans-serif;color:black;'>Content Disclaimer</span></strong></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Lato",sans-serif;color:black;'>The information contained in this website is provided for informational purposes only. &nbsp;The transmission and receipt of information contained on this website, in whole or in part, or communication with PROFESSIONAL LINKS, LLC via the Internet or email through this website does not constitute or create a fiduciary relationship between us and any recipient. You should not send us any confidential information in response to this webpage. &nbsp;The material on this website may not reflect the most current developments. We disclaim all liability in respect to actions taken or not taken based on any or all the contents of this site to the fullest extent permitted by law. The information in this website should not be viewed as an offer to perform services in any jurisdiction other than those in which PROFESSIONAL LINKS, LLC is licensed to practice. No past results serve in any way as a guarantee of future results.</span></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style='font-family:"Lato",sans-serif;color:black;'>Governing Law</span></strong></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Lato",sans-serif;color:black;'>The laws of the State of California shall govern any disputes arising out of or relating to this Website, or the services listed on the Website. By visiting the Website, you further agree that the laws of the State of California, without regard to principles of conflict of laws, will govern these terms and conditions of use, and any dispute of any sort that might arise between you and PROFESSIONAL LINKS, LLC.</span></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style='font-family:"Lato",sans-serif;color:black;'>Disputes</span></strong></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Lato",sans-serif;color:black;'>Any dispute relating in any way to your visit to the Website shall be submitted to confidential binding arbitration in Orange County, California, except that, to the extent you have in any manner violated or threatened to violate our intellectual property rights, PROFESSIONAL LINKS, LLCmay seek injunctive or other appropriate relief in any state or federal court in the State of California, and you consent to the exclusive jurisdiction and venue in such courts. &nbsp;Arbitration under these terms and conditions of use shall be conducted under the rules then prevailing of the American Arbitration Association. The arbitrator&rsquo;s award shall be binding and may be entered as a judgment in any court of competent jurisdiction. To the fullest extent permitted by applicable law, no arbitration under these terms and conditions of use shall be joined to an arbitration involving any other party subject to these terms and conditions of use, whether through class arbitration proceedings or otherwise.</span></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style='font-family:"Lato",sans-serif;color:black;'>Website Policies, Modification, and Severability</span></strong></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Lato",sans-serif;color:black;'>As noted above, you are encouraged and advised to review the terms and conditions of use and privacy policy posted on the Website. These policies govern your visit to the Website. By using the Website, you agree to be bound by and to abide by these policies, just as if you had signed an agreement.&nbsp;</span></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Lato",sans-serif;color:black;'>We reserve the right, in our sole discretion, to change, modify, add to, or remove portions of the Website, the terms and conditions of use and the privacy policy at any time. You should check these terms and conditions of use and privacy policy periodically for changes. &nbsp;</span></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Lato",sans-serif;color:black;'>By using the Website after we post any changes to the terms and conditions of use or the privacy policy, you agree to accept those changes, regardless of whether you have reviewed them. If you do not agree to these terms and conditions of use and the privacy policy, you should not use the Website.&nbsp;</span></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Lato",sans-serif;color:black;'>YOUR CONTINUED USE OF THE WEBSITE FOLLOWING OUR POSTING OF A CHANGE NOTICE WILL CONSTITUTE BINDING ACCEPTANCE OF THOSE CHANGES.</span></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Lato",sans-serif;color:black;'>If any of these terms or conditions is deemed invalid, void, or for any reason unenforceable, that condition will be deemed severed and will not affect the validity and enforceability of any remaining condition. Headings are for reference purposes only and in no way define, limit, construe or describe the scope or extent of such section.&nbsp;</span></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Lato",sans-serif;color:black;'>If you do not comply with these terms and we do not take action immediately, this doesn&rsquo;t mean that we are giving up any rights that we may have (such as taking action in the future).</span></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Lato",sans-serif;color:black;'>Our decision not to enforce any right or decision not to act with respect to any breach by you under the Terms will not constitute a waiver of that right nor a waiver of our right to act with respect to subsequent or similar breaches.&nbsp;</span></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Lato",sans-serif;color:black;'>We shall have the right to assign these terms. You may not assign, in whole or part, the terms to any person or entity. This constitutes the entire agreement between you and PROFESSIONAL LINKS, LLC and governs your use of the Website, superseding any prior written or oral agreements in relation to the same subject matter herein.</span></p>


        </div>
        <!--Body-->


        <home-footer/>
    </div>
</template>
<script>
    import HeaderNavBar from "../home/components/header/header-nav-bar";
    import HomeFooter from "../home/components/footer";

    export default {
        name: "Terms",
        props: {
            userId: {},
        },
        components: {
            HeaderNavBar,
            HomeFooter,
        },
    };
</script>
<style lang="scss" scoped>
    div[data-proslinks-homepage] .navbar-custom.fixed-top {
        padding: 0.5rem 1.5rem 0.5rem 2rem !important;
        background-color: #5f4dee !important;
        -webkit-box-shadow: 0 0.0625rem 0.375rem 0 rgba(0, 0, 0, 0.1) !important;
        box-shadow: 0 0.0625rem 0.375rem 0 rgba(0, 0, 0, 0.1) !important;
    }

    div[data-proslinks-homepage] .header {
        background-color: #5f4dee;
    }

    div[data-proslinks-homepage] .header .header-content {
        padding-top: 0 !important;
        padding-bottom: 4rem !important;
        text-align: center;
    }

</style>
