<template>
    <div style="overflow-x: hidden !important;" data-proslinks-homepage>
        <!--Header-->
        <header-nav-bar></header-nav-bar>
        <header id="header" class="header">
            <div class="header-content"></div>
        </header>
        <!--Header-->


        <!--Body-->
        <div class="container mt-5 mb-5 pt-4 pb-4">
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style='font-family:"Lato",sans-serif;color:red;'>PROFESSIONAL LINKS, LLC</span></strong></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style='font-family:"Lato",sans-serif;color:red;'>Website Privacy Policy</span></strong></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style='font-family:"Lato",sans-serif;color:red;'>Revised as of &nbsp;January 15, 2021</span></strong></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Lato",sans-serif;color:black;'>The website located at www.skillpeers.com (the &ldquo;Website&rdquo;) is operated by PROFESSIONAL LINKS, LLC &nbsp;(hereinafter may be referred to as &ldquo;us,&rdquo; &ldquo;we,&rdquo; and &ldquo;our&rdquo;). PROFESSIONAL LINKS, LLC has created this privacy policy to demonstrate our commitment to the privacy of our visitors and customers. PROFESSIONAL LINKS, LLC &nbsp;is committed to respecting your privacy and recognizing your need for appropriate protection and management of personally identifiable information you share with us (the phrases &ldquo;personally identifiable information&rdquo; and &ldquo;personal information&rdquo; may mean any information by which you, individually, can be identified, such as your name, address, telephone number, etc.). The purpose of this privacy policy is to inform you when you visit our Website how we use such information.</span></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Lato",sans-serif;color:black;'>This Privacy Policy also governs the collection, use, transfer, and processing of your personal information. By using this Website, you consent to our Privacy Policy set out below. All terms not defined in this document have the meaning ascribed to in the Website Terms and Conditions of Use located at http://www.skillpeers.com/#/terms.&nbsp;</span></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Lato",sans-serif;color:black;'>PROFESSIONAL LINKS, LLC &nbsp;is a United States Corporation subject to the laws of the United States. The United States may not offer a level of privacy protection as great as that offered in other jurisdictions. Since our servers are located in the United States, your data may be transferred to, stored, or processed in the United States. By using our Services, you understand and consent to the collection, storage, processing, and transfer of your data to our facilities in the United States and those third parties we share your data with as described in this Policy and our Terms and Conditions of Use.</span></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style='font-family:"Lato",sans-serif;color:black;'>A Special Notice about Children</span></strong></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Lato",sans-serif;color:black;'>Children (under the age of 18) are not eligible to use the Website unsupervised, and we ask that children do not submit any personal information to us. If you are under the age of 18, you may only use this Website in conjunction with, and under the supervision of your parents or guardians.</span></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style='font-family:"Lato",sans-serif;color:black;'>Users Under 13 Years of Age</span></strong></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Lato",sans-serif;color:black;'>The Website is not directed to children under the age of 13. &nbsp;We do not knowingly collect information, including Personal Information, from children or other individuals who are not legally able to use our Website and Services. If we obtain actual knowledge that we have collected Personal Information from a child under the age of 13, we will promptly delete it, unless we are legally obligated to retain such data. &nbsp;Contact us if you believe that we have mistakenly or unintentionally collected information from a child under the age of 13, via our contact form or by writing to PROFESSIONAL LINKS, LLC, 11Windrose, Aliso Viejo, CA 92656. By using the Services, you are representing to us that you are not under the age of 13.</span></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style='font-family:"Lato",sans-serif;color:black;'>General</span></strong></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Lato",sans-serif;color:black;'>In general, you may visit the Website without telling us who you are or revealing any of your personal information. There are two primary ways PROFESSIONAL LINKS, LLC &nbsp;will collect your personal information:</span></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Lato",sans-serif;color:black;'>First, PROFESSIONAL LINKS, LLC &nbsp;may collect information submitted via the &ldquo;Contact Us&rdquo; form, requesting or downloading one of our publications, sending us an email, telephoning us, or by subscribing to our news feed, including any personal information you submit. Whether or not you choose to provide personal information is entirely up to you.</span></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Lato",sans-serif;color:black;'>Second, PROFESSIONAL LINKS, LLC &nbsp;may track the domain address from which you visit the Website through cookies (see &ldquo;Cookies&rdquo; Section below), analyze this data for trends and statistics, and use the information for internal marketing purposes. PROFESSIONAL LINKS, LLC &nbsp;will never sell your information to third parties.</span></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Lato",sans-serif;color:black;'>The manner in which we will collect and use your information is set forth below.&nbsp;</span></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style='font-family:"Lato",sans-serif;color:black;'>Collection and Use of Personal Information</span></strong></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Lato",sans-serif;color:black;'>We will collect all the information that you supply to us through our contact and sign up forms, including personal information and personal messages you submit. The collection of this information enables us to provide you with the assistance you have requested. &nbsp;In furtherance of these objectives, PROFESSIONAL LINKS, LLC &nbsp;may collect the following personal information:</span></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><u><span style='font-family:"Lato",sans-serif;color:black;'>Contact Information:</span></u><span style='font-family:"Lato",sans-serif;color:black;'>&nbsp;If you submit your name, address, birth date, phone number, email address, or any other personal contact information on our &ldquo;Account Profile form&rdquo;, &nbsp;or via email or other communication mechanism, &nbsp;then you are deemed to have given consent for us to use such information to contact you (&ldquo;Contact Information&rdquo;).&nbsp;</span></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><u><span style='font-family:"Lato",sans-serif;color:black;'>Customer Information</span></u><span style='font-family:"Lato",sans-serif;color:black;'>: We may record and retain records of your specific personal information and messages submitted to us through the &ldquo;Account Profile&rdquo; form or email or other communication mechanism (&ldquo;Customer Information&rdquo;).&nbsp;</span></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><u><span style='font-family:"Lato",sans-serif;color:black;'>Statistical Information:&nbsp;</span></u><span style='font-family:"Lato",sans-serif;color:black;'>We may gather statistical information from website visitors and analyze this data for trends and statistics (&ldquo;Statistical Information&rdquo;).</span></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><u><span style='font-family:"Lato",sans-serif;color:black;'>Collected Information:</span></u><span style='font-family:"Lato",sans-serif;color:black;'>&nbsp;Contact Information, Customer Information, and Statistical Information, and any information we may collect from you through the use of cookies (see &ldquo;Cookies&rdquo; Section below), or from our affiliates or from other parties or through any other means, shall collectively be referred to as (&ldquo;Collected Information&rdquo;).</span></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:.0001pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style='font-family:"Lato",sans-serif;color:black;'>Data Integrity and Purpose Limitation</span></strong></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Lato",sans-serif;color:black;'>We only collect Personal Information that is relevant for providing the Services. We process Personal Information in a way that is compatible with providing the Services or as otherwise authorized by you. We take reasonable steps to ensure that Personal Information is reliable for its intended use, accurate, complete, and current.&nbsp;</span></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style='font-family:"Lato",sans-serif;color:black;'>Safe Harbor</span></strong></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Lato",sans-serif;color:black;'>PROFESSIONAL LINKS, LLC &nbsp;adheres to the U.S. safe harbor policy privacy principles of notice, choice, onward transfer, security, data integrity, access, and enforcement. If you have any questions regarding this policy, contact PROFESSIONAL LINKS, LLC through the Contact Forms or write to us at PROFESSIONAL LINKS, LLC, 11Windrose, Aliso Viejo, CA 92656.</span></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style='font-family:"Lato",sans-serif;color:black;'>Cookies</span></strong></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Lato",sans-serif;color:black;'>The Website may use cookie technology to improve the quality of your experience. A cookie is a small file that contains information sent by a website that is saved on your hard disk by your computer&apos;s browser. Cookies store information that a website may need in order to personalize your experience and gather website statistical data. Any time you visit the Website to browse or to read or download information, cookies may collect and store the name of the domain and host from which you access the Internet (for example, msn.com, google.com, etc.); the Internet protocol (IP) address of the computer you are using; the browser software you use and your operating system; the date and time you access the Website; and the Internet address of the website from which you linked directly to the Website. We may use this information to measure the number of visitors to areas of the Website, and to help us make the Website more useful and interesting to our visitors. We may use cookies to gather statistical information about the Website such as Website visiting patterns to help target advertisements based on User interests.</span></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Lato",sans-serif;color:black;'>Some consumers may not know that cookies are being placed on their computers when they visit websites. If you want to know when this happens, or to prevent it from happening, you can set your browser to advise you when a website attempts to place a cookie on your computer.</span></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style='font-family:"Lato",sans-serif;color:black;'>Do We Share Your Information?</span></strong></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Lato",sans-serif;color:black;'>We may only share your personal information with third-party independent suppliers for purposes of tracking information generated through the Website for marketing purposes. If we engage a third-party independent supplier, they will be obligated not to use or share your personal information for unauthorized purposes.&nbsp;</span></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Lato",sans-serif;color:black;'>We will never sell, rent, or lease your personal information to a third party.</span></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Lato",sans-serif;color:black;'>PROFESSIONAL LINKS, LLC &nbsp;may use your Collected Information in the following ways:</span></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><u><span style='font-family:"Lato",sans-serif;color:black;'>Contact Information:&nbsp;</span></u><span style='font-family:"Lato",sans-serif;color:black;'>We may use your Contact Information to provide information that you have requested, perform a service you requested, send you a requested publication, or send you our news articles as published if you have subscribed to our feed. Specifically, we may use your email address and phone number to contact you.&nbsp;</span></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><u><span style='font-family:"Lato",sans-serif;color:black;'>Customer Information</span></u><span style='font-family:"Lato",sans-serif;color:black;'>: Any Customer Information that you disclose to us may be used to respond to your inquiries submitted to us.</span></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><u><span style='font-family:"Lato",sans-serif;color:black;'>Statistical Information:&nbsp;</span></u><span style='font-family:"Lato",sans-serif;color:black;'>We may use Statistical Information to help diagnose problems with and maintain our computer servers, to manage our Website, and to enhance our Website and services based on the usage pattern data we receive. We may generate reports and analysis based on the Statistical Information for internal analysis, monitoring, and marketing decisions. We may provide Statistical Information to independent third parties for marketing purposes, but when we do so, we will not provide them with any personal information.&nbsp;</span></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style='font-family:"Lato",sans-serif;color:black;'>Other Disclosures</span></strong></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Lato",sans-serif;color:black;'>We may also disclose your personal information to comply with a court order, subpoena, search warrant, or other legal process; to comply with legal, regulatory, or administrative requirements of any governmental authorities; to protect and defend PROFESSIONAL LINKS, LLC, its subsidiaries and affiliates, and their officers, directors, employees, attorneys, agents, contractors, and partners, in connection with any legal action, claim, or dispute; to enforce the Terms and Conditions of Use of the Website; to prevent imminent physical harm; and in the event that we find that your actions on the Website violate any laws.</span></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Lato",sans-serif;color:black;'>We reserve the right to transfer your personal information to a third party in the event of a transfer of all or substantially all of PROFESSIONAL LINKS, LLC &nbsp;assets, provided that the third party agrees to adhere to the terms of this privacy policy.&nbsp;</span></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style='font-family:"Lato",sans-serif;color:black;'>Opt Out</span></strong></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Lato",sans-serif;color:black;'>You may &ldquo;Opt out&rdquo; of having your personal information shared by providing us with written notice identifying which communications you choose not to receive by writing us at: PROFESSIONAL LINKS, LLC, &nbsp;11 Windrose, Aliso Viejo, CA 92656.</span></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style='font-family:"Lato",sans-serif;color:black;'>Data Retention</span></strong></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Lato",sans-serif;color:black;'>We will retain your Personal Information for the period necessary to fulfill the purposes outlined in this Privacy Policy unless a longer retention period is required or allowed by law.</span></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style='font-family:"Lato",sans-serif;color:black;'>Third-Party Hosting</span></strong></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Lato",sans-serif;color:black;'>We may contract with third parties to maintain and host the Website. Any information you submit to us, including personal information, may be placed and stored on a computer server maintained by this third-party host.&nbsp;</span></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:.0001pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style='font-family:"Lato",sans-serif;color:black;'>Website Technologies</span></strong></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Lato",sans-serif;color:black;'>PROFESSIONAL LINKS, LLC &nbsp;does not provide the technologies used to build this Website, and therefore, neither recommends nor endorses the same. Any information regarding identified technologies, including their capabilities, limitations, and applications, should be sought directly from their manufacturers. PROFESSIONAL LINKS, LLC &nbsp;hereby disclaims any rights to trademarks, service marks, trade names, logos, copyrights, patents, domain names, or other intellectual property interests of third parties.</span></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style='font-family:"Lato",sans-serif;color:black;'>Links to Other Material</span></strong></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Lato",sans-serif;color:black;'>The Website may contain links to other websites, including but not limited to, Facebook, Twitter, LinkedIn, &nbsp;Instagram, Pinterest and the like. These links and plug-ins are for your convenience. Websites linked to and from the Website are not necessarily under the control of PROFESSIONAL LINKS, LLC, and PROFESSIONAL LINKS, LLC shall have no responsibility or liability whatsoever for the content or privacy practices of any linked websites, or any link or linking program at any time. You should read and understand PROFESSIONAL LINKS, LLC &nbsp;policies with respect to such third-party links, as stated in the Terms and Conditions of the Website.</span></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style='font-family:"Lato",sans-serif;color:black;'>Security</span></strong></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Lato",sans-serif;color:black;'>The Website uses commercially reasonable &nbsp;security measures to protect the loss, misuse, and alteration of the information under our control; however no system is impenetrable. &nbsp;</span></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Lato",sans-serif;color:black;'>We use reasonable and appropriate physical, electronic, and administrative safeguards to protect personal data from loss, misuse and unauthorized access, disclosure, alteration and destruction, taking into account the nature of the Personal Information and risks involved in processing that information.</span></p>
          <p style='margin-top:.25in;margin-right:0in;margin-bottom:6.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style='font-size:16px;font-family:"Lato",sans-serif;color:black;'>Your Rights Under the CCPA.</span></strong></p>
          <p style='margin-top:.25in;margin-right:0in;margin-bottom:6.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Lato",sans-serif;color:black;'>You have the right under the California Consumer Privacy Act of 2018 (CCPA) and certain other privacy and data protection laws, as applicable, to exercise free of charge:</span></p>
          <p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Lato",sans-serif;color:black;'>&nbsp;</span></p>
          <table style="border: none;border-collapse:collapse;">
            <tbody>
            <tr>
              <td style="border: 1pt solid black;padding: 5pt 6pt;height: 515.5pt;vertical-align: top;">
                <p style='margin-top:6.0pt;margin-right:0in;margin-bottom:  6.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Lato",sans-serif;color:black;'>Disclosure of Personal Information We Collect About You</span></p>
              </td>
              <td style="border-color: black black black currentcolor;border-style: solid solid solid none;border-width: 1pt 1pt 1pt medium;border-image: none 100% / 1 / 0 stretch;padding: 5pt 6pt;height: 515.5pt;vertical-align: top;">
                <p style='margin-top:6.0pt;margin-right:0in;margin-bottom:  6.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Lato",sans-serif;color:black;'>You have the right to know:</span></p>
                <p style='margin-top:6.0pt;margin-right:0in;margin-bottom:  6.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Lato",sans-serif;color:black;'>&middot;</span><span style='font-size:9px;font-family:"Lato",sans-serif;color:black;'>&nbsp;&nbsp;</span><span style='font-size:16px;font-family:"Lato",sans-serif;color:black;'>The categories of personal information we have collected about you;</span></p>
                <p style='margin-top:6.0pt;margin-right:0in;margin-bottom:  6.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Lato",sans-serif;color:black;'>&middot;</span><span style='font-size:9px;font-family:"Lato",sans-serif;color:black;'>&nbsp;&nbsp;</span><span style='font-size:16px;font-family:"Lato",sans-serif;color:black;'>The categories of sources from which the personal information is collected;</span></p>
                <p style='margin-top:6.0pt;margin-right:0in;margin-bottom:  6.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Lato",sans-serif;color:black;'>&middot;</span><span style='font-size:9px;font-family:"Lato",sans-serif;color:black;'>&nbsp;&nbsp;</span><span style='font-size:16px;font-family:"Lato",sans-serif;color:black;'>Our business or commercial purpose for collecting or selling personal information;</span></p>
                <p style='margin-top:6.0pt;margin-right:0in;margin-bottom:  6.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Lato",sans-serif;color:black;'>&middot;</span><span style='font-size:9px;font-family:"Lato",sans-serif;color:black;'>&nbsp;&nbsp;</span><span style='font-size:16px;font-family:"Lato",sans-serif;color:black;'>The categories of third parties with whom we share personal information, if any; and</span></p>
                <p style='margin-top:6.0pt;margin-right:0in;margin-bottom:  6.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Lato",sans-serif;color:black;'>&middot;</span><span style='font-size:9px;font-family:"Lato",sans-serif;color:black;'>&nbsp;&nbsp;</span><span style='font-size:16px;font-family:"Lato",sans-serif;color:black;'>The specific pieces of personal information we have collected about you.</span></p>
                <p style='margin-top:6.0pt;margin-right:0in;margin-bottom:  6.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Lato",sans-serif;color:black;'>Please note that we are not required to:</span></p>
                <p style='margin-top:6.0pt;margin-right:0in;margin-bottom:  6.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Lato",sans-serif;color:black;'>&middot;</span><span style='font-size:9px;font-family:"Lato",sans-serif;color:black;'>&nbsp;&nbsp;</span><span style='font-size:16px;font-family:"Lato",sans-serif;color:black;'>Retain any personal information about you that was collected for a single one-time transaction if, in the ordinary course of business, that information about you is not retained;</span></p>
                <p style='margin-top:6.0pt;margin-right:0in;margin-bottom:  6.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Lato",sans-serif;color:black;'>&middot;</span><span style='font-size:9px;font-family:"Lato",sans-serif;color:black;'>&nbsp;&nbsp;</span><span style='font-size:16px;font-family:"Lato",sans-serif;color:black;'>Reidentify or otherwise link any data that, in the ordinary course of business, is not maintained in a manner that would be considered personal information; or</span></p>
                <p style='margin-top:6.0pt;margin-right:0in;margin-bottom:  6.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Lato",sans-serif;color:black;'>&middot;</span><span style='font-size:9px;font-family:"Lato",sans-serif;color:black;'>&nbsp;&nbsp;</span><span style='font-size:16px;font-family:"Lato",sans-serif;color:black;'>Provide the personal information to you more than twice in a 12-month period.</span></p>
              </td>
            </tr>
            <tr>
              <td style="border-color: currentcolor black black;border-style: none solid solid;border-width: medium 1pt 1pt;border-image: none 100% / 1 / 0 stretch;padding: 5pt 6pt;height: 424.75pt;vertical-align: top;">
                <p style='margin-top:6.0pt;margin-right:0in;margin-bottom:  6.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Lato",sans-serif;color:black;'>Personal Information Sold or Used for a Business Purpose</span></p>
              </td>
              <td style="border-color: currentcolor black black currentcolor;border-style: none solid solid none;border-width: medium 1pt 1pt medium;padding: 5pt 6pt;height: 424.75pt;vertical-align: top;">
                <p style='margin-top:6.0pt;margin-right:0in;margin-bottom:  6.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Lato",sans-serif;color:black;'>In connection with any personal information we may sell or disclose to a third party for a business purpose, you have the right to know:</span></p>
                <p style='margin-top:6.0pt;margin-right:0in;margin-bottom:  6.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Lato",sans-serif;color:black;'>The categories of personal information about you that we sold and the categories of third parties to whom the personal information was sold; and</span></p>
                <p style='margin-top:6.0pt;margin-right:0in;margin-bottom:  6.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Lato",sans-serif;color:black;'>The categories of personal information that we disclosed about you for a business purpose.</span></p>
                <p style='margin-top:6.0pt;margin-right:0in;margin-bottom:  6.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Lato",sans-serif;color:black;'>You have the right under the California Consumer Privacy Act of 2018 (CCPA) and certain other privacy and data protection laws, as applicable, to opt-out of the sale [or disclosure] of your personal information. If you exercise your right to opt-out of the sale [or disclosure] of your personal information, we will refrain from selling your personal information, unless you subsequently provide express authorization for the sale of your personal information.&nbsp;</span></p>
                <p style='margin-top:6.0pt;margin-right:0in;margin-bottom:  6.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Lato",sans-serif;color:black;'>You may &ldquo;Opt out&rdquo; of having your personal information shared by providing us with written notice identifying which communications you choose not to receive by writing us at: PROFESSIONAL LINKS, LLC, &nbsp;11 Windrose, Aliso Viejo, CA 92656.</span></p>
              </td>
            </tr>
            <tr>
              <td style="border-color: currentcolor black black;border-style: none solid solid;border-width: medium 1pt 1pt;border-image: none 100% / 1 / 0 stretch;padding: 5pt 6pt;height: 913.75pt;vertical-align: top;">
                <p style='margin-top:6.0pt;margin-right:0in;margin-bottom:  6.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Lato",sans-serif;color:black;'>Right to Deletion</span></p>
              </td>
              <td style="border-color: currentcolor black black currentcolor;border-style: none solid solid none;border-width: medium 1pt 1pt medium;padding: 5pt 6pt;height: 913.75pt;vertical-align: top;">
                <p style='margin-top:6.0pt;margin-right:0in;margin-bottom:  6.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Lato",sans-serif;color:black;'>Subject to certain exceptions set out below, on receipt of a verifiable request from you, we will:</span></p>
                <p style='margin-top:6.0pt;margin-right:0in;margin-bottom:  6.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Lato",sans-serif;color:black;'>&middot;</span><span style='font-size:9px;font-family:"Lato",sans-serif;color:black;'>&nbsp;&nbsp;</span><span style='font-size:16px;font-family:"Lato",sans-serif;color:black;'>Delete your personal information from our records; and</span></p>
                <p style='margin-top:6.0pt;margin-right:0in;margin-bottom:  6.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Lato",sans-serif;color:black;'>&middot;</span><span style='font-size:9px;font-family:"Lato",sans-serif;color:black;'>&nbsp;&nbsp;</span><span style='font-size:16px;font-family:"Lato",sans-serif;color:black;'>Direct any service providers to delete your personal information from their records.</span></p>
                <p style='margin-top:6.0pt;margin-right:0in;margin-bottom:  6.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Lato",sans-serif;color:black;'>&middot;</span><span style='font-size:9px;font-family:"Lato",sans-serif;color:black;'>&nbsp;&nbsp;</span><span style='font-size:16px;font-family:"Lato",sans-serif;color:black;'>Please note that we may not delete your personal information if it is necessary to:</span></p>
                <p style='margin-top:6.0pt;margin-right:0in;margin-bottom:  6.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Lato",sans-serif;color:black;'>&middot;</span><span style='font-size:9px;font-family:"Lato",sans-serif;color:black;'>&nbsp;&nbsp;</span><span style='font-size:16px;font-family:"Lato",sans-serif;color:black;'>Complete the transaction for which the personal information was collected, fulfill the terms of a written warranty or product recall conducted in accordance with federal law, provide a good or service requested by you, or reasonably anticipated within the context of our ongoing business relationship with you, or otherwise perform a contract between you and us;</span></p>
                <p style='margin-top:6.0pt;margin-right:0in;margin-bottom:  6.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Lato",sans-serif;color:black;'>&middot;</span><span style='font-size:9px;font-family:"Lato",sans-serif;color:black;'>&nbsp;&nbsp;</span><span style='font-size:16px;font-family:"Lato",sans-serif;color:black;'>Detect security incidents, protect against malicious, deceptive, fraudulent, or illegal activity; or prosecute those responsible for that activity;</span></p>
                <p style='margin-top:6.0pt;margin-right:0in;margin-bottom:  6.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Lato",sans-serif;color:black;'>&middot;</span><span style='font-size:9px;font-family:"Lato",sans-serif;color:black;'>&nbsp;&nbsp;</span><span style='font-size:16px;font-family:"Lato",sans-serif;color:black;'>Debug to identify and repair errors that impair existing intended functionality;</span></p>
                <p style='margin-top:6.0pt;margin-right:0in;margin-bottom:  6.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Lato",sans-serif;color:black;'>&middot;</span><span style='font-size:9px;font-family:"Lato",sans-serif;color:black;'>&nbsp;&nbsp;</span><span style='font-size:16px;font-family:"Lato",sans-serif;color:black;'>Exercise free speech, ensure the right of another consumer to exercise his or her right of free speech, or exercise another right provided for by law;</span></p>
                <p style='margin-top:6.0pt;margin-right:0in;margin-bottom:  6.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Lato",sans-serif;color:black;'>&middot;</span><span style='font-size:9px;font-family:"Lato",sans-serif;color:black;'>&nbsp;&nbsp;</span><span style='font-size:16px;font-family:"Lato",sans-serif;color:black;'>Comply with the California Electronic Communications Privacy Act;</span></p>
                <p style='margin-top:6.0pt;margin-right:0in;margin-bottom:  6.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Lato",sans-serif;color:black;'>&middot;</span><span style='font-size:9px;font-family:"Lato",sans-serif;color:black;'>&nbsp;&nbsp;</span><span style='font-size:16px;font-family:"Lato",sans-serif;color:black;'>Engage in public or peer-reviewed scientific, historical, or statistical research in the public interest that adheres to all other applicable ethics and privacy laws, when our deletion of the information is likely to render impossible or seriously impair the achievement of such research, provided we have obtained your informed consent;</span></p>
                <p style='margin-top:6.0pt;margin-right:0in;margin-bottom:  6.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Lato",sans-serif;color:black;'>&middot;</span><span style='font-size:9px;font-family:"Lato",sans-serif;color:black;'>&nbsp;&nbsp;</span><span style='font-size:16px;font-family:"Lato",sans-serif;color:black;'>Enable solely internal uses that are reasonably aligned with your expectations based on your relationship with us;</span></p>
                <p style='margin-top:6.0pt;margin-right:0in;margin-bottom:  6.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Lato",sans-serif;color:black;'>&middot;</span><span style='font-size:9px;font-family:"Lato",sans-serif;color:black;'>&nbsp;&nbsp;</span><span style='font-size:16px;font-family:"Lato",sans-serif;color:black;'>Comply with an existing legal obligation; or</span></p>
                <p style='margin-top:6.0pt;margin-right:0in;margin-bottom:  6.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Lato",sans-serif;color:black;'>&middot;</span><span style='font-size:9px;font-family:"Lato",sans-serif;color:black;'>&nbsp;&nbsp;</span><span style='font-size:16px;font-family:"Lato",sans-serif;color:black;'>Otherwise use your personal information, internally, in a lawful manner that is compatible with the context in which you provided the information.</span></p>
              </td>
            </tr>
            <tr>
              <td style="border-color: currentcolor black black;border-style: none solid solid;border-width: medium 1pt 1pt;border-image: none 100% / 1 / 0 stretch;padding: 5pt 6pt;height: 352.75pt;vertical-align: top;">
                <p style='margin-top:6.0pt;margin-right:0in;margin-bottom:  6.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Lato",sans-serif;color:black;'>Protection Against Discrimination</span></p>
              </td>
              <td style="border-color: currentcolor black black currentcolor;border-style: none solid solid none;border-width: medium 1pt 1pt medium;padding: 5pt 6pt;height: 352.75pt;vertical-align: top;">
                <p style='margin-top:6.0pt;margin-right:0in;margin-bottom:  6.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Lato",sans-serif;color:black;'>You have the right to not be discriminated against by us because you exercised any of your rights under the CCPA. This means we cannot, among other things:</span></p>
                <p style='margin-top:6.0pt;margin-right:0in;margin-bottom:  6.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Lato",sans-serif;color:black;'>&middot;</span><span style='font-size:9px;font-family:"Lato",sans-serif;color:black;'>&nbsp;&nbsp;</span><span style='font-size:16px;font-family:"Lato",sans-serif;color:black;'>Deny goods or services to you;</span></p>
                <p style='margin-top:6.0pt;margin-right:0in;margin-bottom:  6.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Lato",sans-serif;color:black;'>&middot;</span><span style='font-size:9px;font-family:"Lato",sans-serif;color:black;'>&nbsp;&nbsp;</span><span style='font-size:16px;font-family:"Lato",sans-serif;color:black;'>Charge different prices or rates for goods or services, including through the use of discounts or other benefits or imposing penalties;</span></p>
                <p style='margin-top:6.0pt;margin-right:0in;margin-bottom:  6.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Lato",sans-serif;color:black;'>&middot;</span><span style='font-size:9px;font-family:"Lato",sans-serif;color:black;'>&nbsp;&nbsp;</span><span style='font-size:16px;font-family:"Lato",sans-serif;color:black;'>Provide a different level or quality of goods or services to you; or</span></p>
                <p style='margin-top:6.0pt;margin-right:0in;margin-bottom:  6.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Lato",sans-serif;color:black;'>&middot;</span><span style='font-size:9px;font-family:"Lato",sans-serif;color:black;'>&nbsp;&nbsp;</span><span style='font-size:16px;font-family:"Lato",sans-serif;color:black;'>Suggest that you will receive a different price or rate for goods or services or a different level or quality of goods or services.</span></p>
                <p style='margin-top:6.0pt;margin-right:0in;margin-bottom:  6.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Lato",sans-serif;color:black;'>Please note that we may charge a different price or rate or provide a different level or quality of [goods and/or services] to you, if that difference is reasonably related to the value provided to our business by your personal information.</span></p>
              </td>
            </tr>
            </tbody>
          </table>
          <p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;color:black;'>&nbsp;</span></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:12.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style='font-family:"Lato",sans-serif;color:black;'>Privacy Rights Notice to California Residents</span></strong></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Lato",sans-serif;color:black;'>The State of California enacted the Shine the Light law (California Civil Code Section 1798.83) that permits users who are California residents to request certain information regarding the disclosure of certain &ldquo;personal information&rdquo; during the past year for marketing purposes. To make such a request, please contact us using our contact form or alternatively write us at PROFESSIONAL LINKS, LLC, &nbsp;11Windrose, Aliso Viejo, CA 92656.</span></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style='font-family:"Lato",sans-serif;color:black;'>How to Exercise Your Rights</span></strong></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Lato",sans-serif;color:black;'>If you would like to exercise any of your rights as described in this Privacy Policy, please contact us by email at&nbsp;</span><a href="mailto:infor@skillpeers.com"><span style='font-family:"Lato",sans-serif;color:#1155CC;'>infor@skillpeers.com</span></a><span style='font-family:"Lato",sans-serif;color:black;'>&nbsp;or alternatively write us at PROFESSIONAL LINKS, LLC, &nbsp;11Windrose, Aliso Viejo, CA 92656.</span></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Lato",sans-serif;color:black;'>Please note that you may only make a CCPA-related data access or data portability disclosure request twice within a 12-month period.</span></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Lato",sans-serif;color:black;'>If you choose to contact directly, you will need to provide us with:</span></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Lato",sans-serif;color:black;'>&bull;Enough information to identify you [(e.g., your full name, address and customer or matter reference number))];</span></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Lato",sans-serif;color:black;'>&bull;Proof of your identity and address (e.g., a copy of your driving license or passport and a recent utility or credit card bill); and</span></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Lato",sans-serif;color:black;'>&bull;A description of what right you want to exercise and the information to which your request relates.</span></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Lato",sans-serif;color:black;'>We are not obligated to make a data access or data portability disclosure if we cannot verify that the person making the request is the person about whom we collected information, or is someone authorized to act on such person&rsquo;s behalf.</span></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Lato",sans-serif;color:black;'>Any personal information we collect from you to verify your identity in connection with your request will be used solely for the purposes of verification.</span></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style='font-family:"Lato",sans-serif;color:black;'>Effective Date and Changes</span></strong></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Lato",sans-serif;color:black;'>This privacy policy is effective as of January 15, 2021. &nbsp;PROFESSIONAL LINKS, LLC &nbsp;reserves the right to revise this Privacy Policy from time to time to reflect changes to our business, the Website or Services, or applicable laws. The revised Privacy Policy will be effective as of the published effective date.</span></p>
          <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Lato",sans-serif;color:black;'>YOUR CONTINUED USE OF THE WEBSITE FOLLOWING OUR POSTING OF A CHANGE NOTICE WILL CONSTITUTE BINDING ACCEPTANCE OF THOSE CHANGES.</span></p>
        </div>
        <!--Body-->


        <home-footer/>
    </div>
</template>
<script>
    import HeaderNavBar from "../home/components/header/header-nav-bar";
    import HomeFooter from "../home/components/footer";

    export default {
        name: "Policy",
        props: {
            userId: {},
        },
        components: {
            HeaderNavBar,
            HomeFooter,
        },
    };
</script>
<style lang="scss" scoped>
    div[data-proslinks-homepage] .navbar-custom.fixed-top {
        padding: 0.5rem 1.5rem 0.5rem 2rem !important;
        background-color: #5f4dee !important;
        -webkit-box-shadow: 0 0.0625rem 0.375rem 0 rgba(0, 0, 0, 0.1) !important;
        box-shadow: 0 0.0625rem 0.375rem 0 rgba(0, 0, 0, 0.1) !important;
    }

    div[data-proslinks-homepage] .header {
        background-color: #5f4dee;
    }

    div[data-proslinks-homepage] .header .header-content {
        padding-top: 0 !important;
        padding-bottom: 4rem !important;
        text-align: center;
    }

</style>
